### ISSUE TITLE
 Failed to execute script docker-compose

### ISSUE THREAD

**Issue by maryammod** [smart-on-fhir/smart-dev-sandbox#18]
I faced the following error when I executed " docker-compose up".

[15008] Failed to execute script docker-compose
Traceback (most recent call last):
  File "site-packages\docker\api\client.py", line 205, in _retrieve_server_version
  File "site-packages\docker\api\daemon.py", line 181, in version

I'd appreciate it if you can enlighten me on how I can fix it.

Thanks,
Maryam

**Comment by vlad-ignatov** [comment]
Looks like a Docker error which I haven't had before. You can try updating docker or running `sudo docker-compose up`.

**Comment by maryammod** [comment]
The docker version and apt-get have been updated and it works.
 Thanks.
